### ISSUE TITLE
get_keys.py IndexError

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#197]
When running `devel/get_keys.py` to get the list of possible keybindings, I receive an error. It happens with both python2 and python3. It happens when using the master branch.

```
[...]
# thread_view.multi.toggle=t # Toggle marked, default: t
# thread_view.multi.save=s # Save marked, default: s
# thread_view.multi.print=p # Print marked messages, default: p
Traceback (most recent call last):
  File "./get_keys.py", line 90, in <module>
    main(*sys.argv[1:])
  File "./get_keys.py", line 76, in main
    if args[1][0] == '"':
IndexError: list index out of range
```

**Comment by gauteh** [comment]
@emdete

**Comment by gauteh** [comment]
should be fixed in latest master.
