### ISSUE TITLE
Polling / Idle Crash

### ISSUE THREAD

**Issue by moddx** [astroidmail/astroid#335]
I just updated from v0.7-1 (AUR) to 

a) v0.9.1-1  from the AUR
b) v0.9.1-2-gaf5d087d right from git

Both versions randomly crash after some time of idling.

Following are two stacktraces of the crash:

```
May 03 19:17:43 tuxship kernel: astroid[17030]: segfault at 10 ip 00007f3b5b530978 sp 00007f3b415724d0 error 4 in libsigc-2.0.so.0.0.0[7f3b5b52d000+5000]
May 03 19:17:43 tuxship systemd[1]: Started Process Core Dump (PID 17032/UID 0).
May 03 19:17:43 tuxship systemd-coredump[17035]: Process 16361 (astroid) of user 1000 dumped core.
                                                 
    Stack trace of thread 17030:
    #0  0x00007f3b5b530978 _ZN4sigc8internal23trackable_callback_list15remove_callbackEPv (libsigc-2.0.so.0)
    #1  0x000000000061702c _ZNK4sigc8internal14slot_do_unbindclEPKNS_9trackableE (astroid)
    #2  0x000000000062cecc _ZN4sigc8internal17with_type_pointerILb1ENS_9trackableENS0_20limit_derived_targetIPS2_NS0_14slot_do_unbindEEEE8execute_ERKS2_RKS6_ (astroid)
    #3  0x000000000062ca95 _ZNK4sigc8internal20limit_derived_targetIPNS_9trackableENS0_14slot_do_unbindEEclIS2_EEvRKT_ (astroid)
    #4  0x000000000062c64b _ZN4sigc7visitorINS_9trackableEE13do_visit_eachINS_8internal20limit_derived_targetIPS1_NS4_14slot_do_unbindEEEEEvRKT_RKS1_ (astroid)
    #5  0x000000000062c156 _ZN4sigc10visit_eachINS_8internal20limit_derived_targetIPNS_9trackableENS1_14slot_do_unbindEEES3_EEvRKT_RKT0_ (astroid)
    #6  0x00000000006b50b9 _ZN4sigc7visitorINS_15limit_referenceIN7Astroid4PollELb1EEEE13do_visit_eachINS_8internal20limit_derived_targetIPNS_9trackableENS7_14slot_do_unbindEEEEEvRKT_RKS4_ (astroid)
    #7  0x00000000006b5057 _ZN4sigc10visit_eachINS_8internal20limit_derived_targetIPNS_9trackableENS1_14slot_do_unbindEEENS_15limit_referenceIN7Astroid4PollELb1EEEEEvRKT_RKT0_ (astroid)
    #8  0x00000000006b5031 _ZN4sigc7visitorINS_18bound_mem_functor1IbN7Astroid4PollEN4Glib11IOConditionEEEE13do_visit_eachINS_8internal20limit_derived_targetIPNS_9trackableENS9_14slot_do_unbindEEEEEvRKT_RKS6_ (astroid)
    #9  0x00000000006b4f63 _ZN4sigc10visit_eachINS_8internal20limit_derived_targetIPNS_9trackableENS1_14slot_do_unbindEEENS_18bound_mem_functor1IbN7Astroid4PollEN4Glib11IOConditionEEEEEvRKT_RKT0_ (astroid)
    #10 0x00000000006b4e77 _ZN4sigc7visitorINS_15adaptor_functorINS_18bound_mem_functor1IbN7Astroid4PollEN4Glib11IOConditionEEEEEE13do_visit_eachINS_8internal20limit_derived_targetIPNS_9trackableENSB_14slot_do_unbindEEEEEvRKT_RKS8_ (astroid)
    #11 0x00000000006b4cfd _ZN4sigc10visit_eachINS_8internal20limit_derived_targetIPNS_9trackableENS1_14slot_do_unbindEEENS_15adaptor_functorINS_18bound_mem_functor1IbN7Astroid4PollEN4Glib11IOConditionEEEEEEEvRKT_RKT0_ (astroid)
    #12 0x00000000006b4a6a _ZN4sigc15visit_each_typeIPNS_9trackableENS_8internal14slot_do_unbindENS_15adaptor_functorINS_18bound_mem_functor1IbN7Astroid4PollEN4Glib11IOConditionEEEEEEEvRKT0_RKT1_ (astroid)
    #13 0x00000000006b46a4 _ZN4sigc8internal14typed_slot_repINS_18bound_mem_functor1IbN7Astroid4PollEN4Glib11IOConditionEEEE7destroyEPv (astroid)
    #14 0x00007f3b5b530d37 _ZN4sigc9slot_baseD1Ev (libsigc-2.0.so.0)
    #15 0x000000000065a75c _ZN4sigc5slot1IbN4Glib11IOConditionEED2Ev (astroid)
    #16 0x000000000065a778 _ZN4sigc4slotIbN4Glib11IOConditionENS_3nilES3_S3_S3_S3_S3_ED2Ev (astroid)
    #17 0x00000000006b18bc _ZN7Astroid4Poll7do_pollEv (astroid)
    #18 0x00000000006b5302 _ZSt13__invoke_implIvRKMN7Astroid4PollEFvvEPS1_JEET_St21__invoke_memfun_derefOT0_OT1_DpOT2_ (astroid)
    #19 0x00000000006b528f _ZSt8__invokeIRKMN7Astroid4PollEFvvEJPS1_EENSt9result_ofIFOT_DpOT0_EE4typeES9_SC_ (astroid)
    #20 0x00000000006b5240 _ZNKSt12_Mem_fn_baseIMN7Astroid4PollEFvvELb1EEclIJPS1_EEEDTcl8__invokedtdefpT6_M_pmfspcl7forwardIT_Efp_EEEDpOS7_ (astroid)
    #21 0x00000000006b520b _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN7Astroid4PollEFvvEEPS2_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE (astroid)
    #22 0x00000000006b5159 _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN7Astroid4PollEFvvEEPS2_EEclEv (astroid)
    #23 0x00000000006b5138 _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN7Astroid4PollEFvvEEPS4_EEE6_M_runEv (astroid)
    #24 0x00007f3b544b458f execute_native_thread_routine (libstdc++.so.6)
    #25 0x00007f3b53cb82e7 start_thread (libpthread.so.0)
    #26 0x00007f3b539f954f __clone (libc.so.6)
    
    Stack trace of thread 16363:
    #0  0x00007f3b539ef67d poll (libc.so.6)
    #1  0x00007f3b560149b6 n/a (libglib-2.0.so.0)
    #2  0x00007f3b56014acc g_main_context_iteration (libglib-2.0.so.0)
    #3  0x00007f3b56014b11 n/a (libglib-2.0.so.0)
    #4  0x00007f3b5603c295 n/a (libglib-2.0.so.0)
    #5  0x00007f3b53cb82e7 start_thread (libpthread.so.0)
    #6  0x00007f3b539f954f __clone (libc.so.6)
    
    Stack trace of thread 16365:
    #0  0x00007f3b53cbe756 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
    #1  0x00007f3b544ae4cc __gthread_cond_wait (libstdc++.so.6)
    #2  0x00000000007840da wait<Astroid::ActionManager::action_worker()::<lambda()> > (astroid)
    #3  0x0000000000782874 _ZN7Astroid13ActionManager13action_workerEv (astroid)
    #4  0x00000000007869e2 _ZSt13__invoke_implIvRKMN7Astroid13ActionManagerEFvvEPS1_JEET_St21__invoke_memfun_derefOT0_OT1_DpOT2_ (astroid)
    #5  0x000000000078696f _ZSt8__invokeIRKMN7Astroid13ActionManagerEFvvEJPS1_EENSt9result_ofIFOT_DpOT0_EE4typeES9_SC_ (astroid)
    #6  0x0000000000786920 _ZNKSt12_Mem_fn_baseIMN7Astroid13ActionManagerEFvvELb1EEclIJPS1_EEEDTcl8__invokedtdefpT6_M_pmfspcl7forwardIT_Efp_EEEDpOS7_ (astroid)
    #7  0x00000000007868eb _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN7Astroid13ActionManagerEFvvEEPS2_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE (astroid)
    #8  0x0000000000786839 _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN7Astroid13ActionManagerEFvvEEPS2_EEclEv (astroid)
    #9  0x0000000000786818 _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN7Astroid13ActionManagerEFvvEEPS4_EEE6_M_runEv (astroid)
    #10 0x00007f3b544b458f execute_native_thread_routine (libstdc++.so.6)
    #11 0x00007f3b53cb82e7 start_thread (libpthread.so.0)
    #12 0x00007f3b539f954f __clone (libc.so.6)
    
    Stack trace of thread 16361:
    #0  0x00007f3b539ef67d poll (libc.so.6)
    #1  0x00007f3b560149b6 n/a (libglib-2.0.so.0)
    #2  0x00007f3b56014acc g_main_context_iteration (libglib-2.0.so.0)
    #3  0x00007f3b565d000d g_application_run (libgio-2.0.so.0)
    #4  0x0000000000614106 _ZN7Astroid7Astroid3runEiPPc (astroid)
    #5  0x0000000000602e1c main (astroid)
    #6  0x00007f3b5392d511 __libc_start_main (libc.so.6)
    #7  0x0000000000602cfa _start (astroid)
    
    Stack trace of thread 16364:
    #0  0x00007f3b539ef67d poll (libc.so.6)
    #1  0x00007f3b560149b6 n/a (libglib-2.0.so.0)
    #2  0x00007f3b56014d42 g_main_loop_run (libglib-2.0.so.0)
    #3  0x00007f3b565fbff6 n/a (libgio-2.0.so.0)
    #4  0x00007f3b5603c295 n/a (libglib-2.0.so.0)
    #5  0x00007f3b53cb82e7 start_thread (libpthread.so.0)
    #6  0x00007f3b539f954f __clone (libc.so.6)
    
    Stack trace of thread 16378:
    #0  0x00007f3b539ef67d poll (libc.so.6)
    #1  0x00007f3b560149b6 n/a (libglib-2.0.so.0)
    #2  0x00007f3b56014acc g_main_context_iteration (libglib-2.0.so.0)
    #3  0x00007f3b40a4155d n/a (libdconfsettings.so)
    #4  0x00007f3b5603c295 n/a (libglib-2.0.so.0)
    #5  0x00007f3b53cb82e7 start_thread (libpthread.so.0)
    #6  0x00007f3b539f954f __clone (libc.so.6)
```

```
-- Logs begin at Tue 2014-06-17 14:13:06 CEST, end at Wed 2017-05-03 18:26:47 CEST. --
May 03 17:16:08 tuxship kernel: astroid[14611]: segfault at 10 ip 00007f90d849c978 sp 00007f90be3448b0 error 4 in libsigc-2.0.so.0.0.0[7f90d8499000+5000]
May 03 17:16:09 tuxship systemd-coredump[14616]: Process 14315 (astroid) of user 1000 dumped core.

    Stack trace of thread 14611:
    #0  0x00007f90d849c978 _ZN4sigc8internal23trackable_callback_list15remove_callbackEPv (libsigc-2.0.so.0)
    #1  0x000000000050add0 _ZN4sigc8internal14typed_slot_repINS_18bound_mem_functor1IbN7Astroid4PollEN4Glib11IOConditionEEEE7destroyEPv (astroid)
    #2  0x00007f90d849cd37 _ZN4sigc9slot_baseD1Ev (libsigc-2.0.so.0)
    #3  0x000000000050888b _ZN7Astroid4Poll7do_pollEv (astroid)
    #4  0x00007f90d3a8458f execute_native_thread_routine (libstdc++.so.6)
    #5  0x00007f90d359b2e7 start_thread (libpthread.so.0)
    #6  0x00007f90d32dc54f __clone (libc.so.6)

    Stack trace of thread 14315:
    #0  0x00007f90d19f4272 n/a (libpango-1.0.so.0)
    #1  0x00007f90d19f6b08 n/a (libpango-1.0.so.0)
    #2  0x00007f90d19f87f8 n/a (libpango-1.0.so.0)
    #3  0x00007f90d19f8d96 pango_layout_get_size (libpango-1.0.so.0)
    #4  0x000000000057511d _ZN7Astroid27ThreadIndexListCellRenderer11render_dateERKN5Cairo6RefPtrINS1_7ContextEEERN3Gtk6WidgetERKN3Gdk9RectangleE (astroid)
    #5  0x0000000000576633 _ZN7Astroid27ThreadIndexListCellRenderer12render_vfuncERKN5Cairo6RefPtrINS1_7ContextEEERN3Gtk6WidgetERKN3Gdk9RectangleESD_NS7_17CellRendererStateE (astroid)
    #6  0x00007f90d98ef706 _ZN3Gtk18CellRenderer_Class21render_vfunc_callbackEP16_GtkCellRendererP6_cairoP10_GtkWidgetPK20_cairo_rectangle_intS9_20GtkCellRendererState (libgtkmm-3.0.so.1)
    #7  0x00007f90d5621bed gtk_cell_renderer_render (libgtk-3.so.0)
    #8  0x00007f90d56180e2 n/a (libgtk-3.so.0)
    #9  0x00007f90d561abb4 n/a (libgtk-3.so.0)
    #10 0x00007f90d5617c39 n/a (libgtk-3.so.0)
    #11 0x00007f90d5852415 n/a (libgtk-3.so.0)
    #12 0x00007f90d584956b n/a (libgtk-3.so.0)
    #13 0x00007f90d584a11d n/a (libgtk-3.so.0)
    #14 0x00007f90d5768d42 n/a (libgtk-3.so.0)
    #15 0x00007f90d5835722 n/a (libgtk-3.so.0)
    #16 0x00007f90d999a499 _ZN3Gtk6Widget7on_drawERKN5Cairo6RefPtrINS1_7ContextEEE (libgtkmm-3.0.so.1)
    #17 0x00007f90d99a5b71 _ZN3Gtk12Widget_Class13draw_callbackEP10_GtkWidgetP6_cairo (libgtkmm-3.0.so.1)
    #18 0x00007f90d5864d1b n/a (libgtk-3.so.0)
    #19 0x00007f90d5648750 gtk_container_propagate_draw (libgtk-3.so.0)
    #20 0x00007f90d5648832 n/a (libgtk-3.so.0)
    #21 0x00007f90d579660b n/a (libgtk-3.so.0)
    #22 0x00007f90d564d78d n/a (libgtk-3.so.0)
    #23 0x00007f90d56525d0 n/a (libgtk-3.so.0)
    #24 0x00007f90d5794ad1 n/a (libgtk-3.so.0)
    #25 0x00007f90d99a5bfc _ZN3Gtk12Widget_Class13draw_callbackEP10_GtkWidgetP6_cairo (libgtkmm-3.0.so.1)
    #26 0x00007f90d5864d1b n/a (libgtk-3.so.0)
    #27 0x00007f90d5648750 gtk_container_propagate_draw (libgtk-3.so.0)
    #28 0x00007f90d5648832 n/a (libgtk-3.so.0)
    #29 0x00007f90d55fa9f4 n/a (libgtk-3.so.0)
    #30 0x00007f90d564d78d n/a (libgtk-3.so.0)
    #31 0x00007f90d56525d0 n/a (libgtk-3.so.0)
    #32 0x00007f90d55fd471 n/a (libgtk-3.so.0)
    #33 0x00007f90d999a499 _ZN3Gtk6Widget7on_drawERKN5Cairo6RefPtrINS1_7ContextEEE (libgtkmm-3.0.so.1)
    #34 0x00007f90d99a5b71 _ZN3Gtk12Widget_Class13draw_callbackEP10_GtkWidgetP6_cairo (libgtkmm-3.0.so.1)
    #35 0x00007f90d5864d1b n/a (libgtk-3.so.0)
    #36 0x00007f90d5648750 gtk_container_propagate_draw (libgtk-3.so.0)
    #37 0x00007f90d5648832 n/a (libgtk-3.so.0)
    #38 0x00007f90d56926ec n/a (libgtk-3.so.0)
    #39 0x00007f90d99a5bfc _ZN3Gtk12Widget_Class13draw_callbackEP10_GtkWidgetP6_cairo (libgtkmm-3.0.so.1)
    #40 0x00007f90d5864d1b n/a (libgtk-3.so.0)
    #41 0x00007f90d5648750 gtk_container_propagate_draw (libgtk-3.so.0)
    #42 0x00007f90d5748200 n/a (libgtk-3.so.0)
    #43 0x00007f90d564d78d n/a (libgtk-3.so.0)
    #44 0x00007f90d56525d0 n/a (libgtk-3.so.0)
    #45 0x00007f90d5748011 n/a (libgtk-3.so.0)
    #46 0x00007f90d99a5bfc _ZN3Gtk12Widget_Class13draw_callbackEP10_GtkWidgetP6_cairo (libgtkmm-3.0.so.1)
    #47 0x00007f90d5864d1b n/a (libgtk-3.so.0)
    #48 0x00007f90d5648750 gtk_container_propagate_draw (libgtk-3.so.0)
    #49 0x00007f90d5648832 n/a (libgtk-3.so.0)
    #50 0x00007f90d55fa9f4 n/a (libgtk-3.so.0)
    #51 0x00007f90d564d78d n/a (libgtk-3.so.0)
    #52 0x00007f90d56525d0 n/a (libgtk-3.so.0)
    #53 0x00007f90d55fd471 n/a (libgtk-3.so.0)
    #54 0x00007f90d999a499 _ZN3Gtk6Widget7on_drawERKN5Cairo6RefPtrINS1_7ContextEEE (libgtkmm-3.0.so.1)
    #55 0x00007f90d99a5b71 _ZN3Gtk12Widget_Class13draw_callbackEP10_GtkWidgetP6_cairo (libgtkmm-3.0.so.1)
    #56 0x00007f90d5864d1b n/a (libgtk-3.so.0)
    #57 0x00007f90d5648750 gtk_container_propagate_draw (libgtk-3.so.0)
    #58 0x00007f90d573914a n/a (libgtk-3.so.0)
    #59 0x00007f90d564d78d n/a (libgtk-3.so.0)
    #60 0x00007f90d56525d0 n/a (libgtk-3.so.0)
    #61 0x00007f90d55fecf4 n/a (libgtk-3.so.0)
    #62 0x00007f90d56525d0 n/a (libgtk-3.so.0)
    #63 0x00007f90d573b89c n/a (libgtk-3.so.0)

    Stack trace of thread 14316:
    #0  0x00007f90d32d267d poll (libc.so.6)
    #1  0x00007f90d49379b6 n/a (libglib-2.0.so.0)
    #2  0x00007f90d4937acc g_main_context_iteration (libglib-2.0.so.0)
    #3  0x00007f90d4937b11 n/a (libglib-2.0.so.0)
    #4  0x00007f90d495f295 n/a (libglib-2.0.so.0)
    #5  0x00007f90d359b2e7 start_thread (libpthread.so.0)
    #6  0x00007f90d32dc54f __clone (libc.so.6)

    Stack trace of thread 14318:
    #0  0x00007f90d35a1756 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
    #1  0x00007f90d3a7e4cc __gthread_cond_wait (libstdc++.so.6)
    #2  0x00000000005cc6e6 _ZN7Astroid13ActionManager13action_workerEv (astroid)
    #3  0x00007f90d3a8458f execute_native_thread_routine (libstdc++.so.6)
    #4  0x00007f90d359b2e7 start_thread (libpthread.so.0)
    #5  0x00007f90d32dc54f __clone (libc.so.6)

    Stack trace of thread 14317:
    #0  0x00007f90d32d267d poll (libc.so.6)
    #1  0x00007f90d49379b6 n/a (libglib-2.0.so.0)
    #2  0x00007f90d4937d42 g_main_loop_run (libglib-2.0.so.0)
    #3  0x00007f90d4f1eff6 n/a (libgio-2.0.so.0)
    #4  0x00007f90d495f295 n/a (libglib-2.0.so.0)
    #5  0x00007f90d359b2e7 start_thread (libpthread.so.0)
    #6  0x00007f90d32dc54f __clone (libc.so.6)

    Stack trace of thread 14331:
    #0  0x00007f90d32d267d poll (libc.so.6)
    #1  0x00007f90d49379b6 n/a (libglib-2.0.so.0)
    #2  0x00007f90d4937acc g_main_context_iteration (libglib-2.0.so.0)
    #3  0x00007f90bd81355d n/a (libdconfsettings.so)
    #4  0x00007f90d495f295 n/a (libglib-2.0.so.0)
    #5  0x00007f90d359b2e7 start_thread (libpthread.so.0)
    #6  0x00007f90d32dc54f __clone (libc.so.6)
```

**Comment by mxmehl** [comment]
I also noticed strange crashes recently. From the last 2 log entries it seems to be related to polling:

```
[2017-05-02 20:33:53.592887] [0x00007f69884c99c0] [debug] db: thread in query check: 0.18 ms.
[2017-05-02 20:33:53.592922] [0x00007f69884c99c0] [debug] ql: updated: found thread in: 0.234 ms.
[2017-05-02 20:33:53.592948] [0x00007f69884c99c0] [debug] ql: updated
[2017-05-02 20:33:53.593264] [0x00007f69884c99c0] [debug] ql: refresh stats..
[2017-05-02 20:33:53.593533] [0x00007f69884c99c0] [info] db: closing db.
[2017-05-02 20:33:53.593584] [0x00007f69884c99c0] [debug] db: ro: waiting for lock to close..
[2017-05-02 20:33:53.593610] [0x00007f69884c99c0] [debug] db: ro: closing..
[2017-05-02 20:37:54.383221] [0x00007f69884c99c0] [info] poll: periodic poll..
[2017-05-02 20:37:54.383540] [0x00007f69884c99c0] [debug] poll: requested..
[2017-05-02 20:37:54.383723] [0x00007f69884c99c0] [info] db: open db read-only, waiting for lock..
[2017-05-02 20:37:54.383890] [0x00007f69884c99c0] [debug] db: read-only got lock.
[2017-05-02 20:37:54.384696] [0x00007f69884c99c0] [debug] db: open time: 0.961 ms.
[2017-05-02 20:37:54.385036] [0x00007f69884c99c0] [info] db: closing db.
[2017-05-02 20:37:54.385245] [0x00007f69884c99c0] [debug] db: ro: waiting for lock to close..
[2017-05-02 20:37:54.385371] [0x00007f69884c99c0] [debug] db: ro: closing..
[2017-05-02 20:37:54.385478] [0x00007f69884c99c0] [debug] poll: revision before poll: 360313
[2017-05-02 20:37:54.385853] [0x00007f69884c99c0] [info] poll: emitted poll state: true
[2017-05-02 20:37:54.385852] [0x00007f69677fe700] [info] poll: polling: /home/max/.config/astroid/poll.sh
```

and a second crash

```
[2017-05-03 12:42:32.100289] [0x00007f2b676019c0] [debug] charset: utf-8
[2017-05-03 12:42:32.100727] [0x00007f2b676019c0] [debug] create message part: 59 (siblings: 0) (kids: 0) (attachment: true) (viewable: false) (mimetype: application/pdf)
[2017-05-03 12:42:32.100773] [0x00007f2b676019c0] [debug] tv: make preview..
[2017-05-03 12:42:32.100800] [0x00007f2b676019c0] [debug] chunk: body: part
[2017-05-03 12:42:32.100824] [0x00007f2b676019c0] [debug] chunk: plain text (out html: false)
[2017-05-03 12:42:32.100852] [0x00007f2b676019c0] [debug] enc: quoted-printable
[2017-05-03 12:42:32.100878] [0x00007f2b676019c0] [debug] charset: utf-8
[2017-05-03 12:42:32.102470] [0x00007f2b676019c0] [info] chunk: contents: loaded 525943 bytes in 1.398 ms.
[2017-05-03 12:42:32.102574] [0x00007f2b676019c0] [debug] tv: added attachment: 2
[2017-05-03 12:42:32.102663] [0x00007f2b676019c0] [debug] tv: set attachment, mime_type: application/pdf, mtype: application
[2017-05-03 12:42:32.104345] [0x00007f2b676019c0] [debug] tv: no message expanded, showing newest message.
[2017-05-03 12:42:32.104490] [0x00007f2b676019c0] [debug] tv: focusing: Sat, 29 Apr 2017 14:01:18 +0000
[2017-05-03 12:42:32.109769] [0x00007f2b676019c0] [info] tv: ready emitted.
[2017-05-03 12:42:32.112171] [0x00007f2b676019c0] [debug] tv: re-doing scroll.
[2017-05-03 12:42:33.961540] [0x00007f2b676019c0] [debug] extension: destruct.
[2017-05-03 12:42:33.962338] [0x00007f2b676019c0] [debug] tv: deconstruct.
[2017-05-03 12:42:33.964198] [0x00007f2b676019c0] [debug] mt: destruct.
[2017-05-03 12:42:33.964280] [0x00007f2b676019c0] [debug] ms: deconstruct
[2017-05-03 12:42:33.964356] [0x00007f2b676019c0] [debug] chunk: deconstruct.
[2017-05-03 12:42:33.964427] [0x00007f2b676019c0] [debug] chunk: deconstruct.
[2017-05-03 12:42:33.964476] [0x00007f2b676019c0] [debug] chunk: deconstruct.
[2017-05-03 12:42:34.869343] [0x00007f2b676019c0] [info] poll: periodic poll..
[2017-05-03 12:42:34.869638] [0x00007f2b676019c0] [debug] poll: requested..
[2017-05-03 12:42:34.869839] [0x00007f2b676019c0] [info] db: open db read-only, waiting for lock..
[2017-05-03 12:42:34.869974] [0x00007f2b676019c0] [debug] db: read-only got lock.
[2017-05-03 12:42:34.870584] [0x00007f2b676019c0] [debug] db: open time: 0.746 ms.
[2017-05-03 12:42:34.870733] [0x00007f2b676019c0] [info] db: closing db.
[2017-05-03 12:42:34.870863] [0x00007f2b676019c0] [debug] db: ro: waiting for lock to close..
[2017-05-03 12:42:34.870959] [0x00007f2b676019c0] [debug] db: ro: closing..
[2017-05-03 12:42:34.871050] [0x00007f2b676019c0] [debug] poll: revision before poll: 360470
[2017-05-03 12:42:34.871446] [0x00007f2b676019c0] [info] poll: emitted poll state: true
[2017-05-03 12:42:34.871336] [0x00007f2b46eba700] [info] poll: polling: /home/max/.config/astroid/poll.sh
```

**Comment by gauteh** [comment]
Yes, looks like it's related to polling. Stack traces are very helpful,
but I don't immediately see the problem. Is there anything else going on
at the same time during poll? Does a poll take long time?

**Comment by moddx** [comment]
I don't think that the poll takes a long time.
The application crashes the same second the poll starts.

I did not notice any other things happening at the same time. As I wrote above, the application was simply idling in the background. One of my systems is a VM that runs just astroid and a window manager, so I am fairly certain that there are no quirky things happening outside of astroid.

**Comment by gauteh** [comment]
moddx writes on mai 4, 2017 23:58:
> I don't think that the poll takes a long time.
> The application crashes the same second the poll starts.
> 
> I did not notice any other things happening at the same time. As I wrote above, the application was simply idling in the background. One of my systems is a VM that runs just astroid and a window manager, so I am fairly certain that there are no quirky things happening outside of astroid.

Great! that's a good testing environment. Would you mind running astroid
through gdb so that you could print a stacktrace when the crash happens?
Or store the cores so that you can print them in retrospect (using
coredumpctl or equiv.). Need as many cores/bts as possible.

What distro are you running in the VM? Are all libraries updated?

**Comment by gauteh** [comment]
Sorry, I mixed up users. You already provide stacktraces, anyway more the better.

**Comment by mxmehl** [comment]
So the random crashes keep happening. It must be caused by something added recently because I've never experienced that before. Or it's something caused by a notmuch/offlineimap update.

How can I create a more verbose stacktrace like @moddx did?

**Comment by gauteh** [comment]
@mxmehl: You set your distro to store coredumps (ulimit, etc) and compile astroid using debug flags, then you can use e.g. `coredumpctl` to get the core dump afterwards (depending on distro). Alternatively, you can run astroid through gdb: `$ gdb --args ./astroid`, when astroid crashes, type `bt` to get a back trace.

**Comment by gauteh** [comment]
Max writes on mai 7, 2017 16:58:
> So the random crashes keep happening. It must be caused by something added recently because I've never experienced that before. Or it's something caused by a notmuch/offlineimap update.

I don't experience any of these crashes, if you experience them
relatively often you can try to use git bisect to identify the commit
that introduced the buggy code. I am guessing it is in the range
6f694ae5db61c25365c7dd682c86726910838324..19a0af6baf493f2ee1b239efc0d89a68fd4b2d22 .

**Comment by gauteh** [comment]
Please try #345

**Comment by mxmehl** [comment]
I'm on *7a92d and the crashes still happen regularly:

```
[15:21:54.562087] [0x00007ffff7ef4a00] [debug] db: ro: closing..
[15:25:54.675051] [0x00007ffff7ef4a00] [info] poll: periodic poll..
[15:25:54.675323] [0x00007ffff7ef4a00] [debug] poll: requested..
[15:25:54.675464] [0x00007ffff7ef4a00] [info] db: open db read-only, waiting for lock..
[15:25:54.675556] [0x00007ffff7ef4a00] [debug] db: read-only got lock.
[15:25:54.676056] [0x00007ffff7ef4a00] [debug] db: open time: 0.591 ms.
[15:25:54.676190] [0x00007ffff7ef4a00] [info] db: closing db.
[15:25:54.676312] [0x00007ffff7ef4a00] [debug] db: ro: waiting for lock to close..
[15:25:54.676438] [0x00007ffff7ef4a00] [debug] db: ro: closing..
[15:25:54.676530] [0x00007ffff7ef4a00] [debug] poll: revision before poll: 373717
[New Thread 0x7fffd6ffd700 (LWP 13341)]
[15:25:54.677219] [0x00007fffd6ffd700] [info] poll: polling: /home/max/.config/astroid/poll.sh
[15:25:54.677278] [0x00007ffff7ef4a00] [info] poll: emitted poll state: true

Thread 28 "astroid" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd6ffd700 (LWP 13341)]
0x00007fffedcb6b9b in malloc_consolidate () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fffedcb6b9b in malloc_consolidate () at /usr/lib/libc.so.6
#1  0x00007fffedcb868a in _int_malloc () at /usr/lib/libc.so.6
#2  0x00007fffedcbaea6 in calloc () at /usr/lib/libc.so.6
#3  0x00007ffff034ae21 in g_malloc0 () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff0363464 in g_slice_alloc () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff036382e in g_slice_alloc0 () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff03431bb in g_source_new () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff5ce9a13 in Glib::Source::Source() () at /usr/lib/libglibmm-2.4.so.1
#8  0x00007ffff5cea27c in Glib::IOSource::IOSource(int, Glib::IOCondition) ()
    at /usr/lib/libglibmm-2.4.so.1
#9  0x00007ffff5cea2fe in Glib::IOSource::create(int, Glib::IOCondition) ()
    at /usr/lib/libglibmm-2.4.so.1
#10 0x00007ffff5cea6b3 in Glib::SignalIO::connect(sigc::slot<bool, Glib::IOCondition, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil> const&, int, Glib::IOCondition, int) () at /usr/lib/libglibmm-2.4.so.1
#11 0x00000000006b1939 in Astroid::Poll::do_poll() (this=0xe2de00)
    at src/poll.cc:220
#12 0x00000000006b594e in std::__invoke_impl<void, void (Astroid::Poll::* const&)(), Astroid::Poll*>(std::__invoke_memfun_deref, void (Astroid::Poll::* const&)(), Astroid::Poll*&&) (__f=@0xeee310: (void (Astroid::Poll::*)(Astroid::Poll * const)) 0x6b1392 <Astroid::Poll::do_poll()>, __t=<unknown type in /usr/bin/astroid, CU 0x316390, DIE 0x3466da>) at /usr/include/c++/6.3.1/functional:227
#13 0x00000000006b58db in std::__invoke<void (Astroid::Poll::* const&)(), Astroid::Poll*>(void (Astroid::Poll::* const&)(), Astroid::Poll*&&) (__fn=@0xeee310: (void (Astroid::Poll::*)(Astroid::Poll * const)) 0x6b1392 <Astroid::Poll::do_poll()>, __args#0=<unknown type in /usr/bin/astroid, CU 0x316390, DIE 0x3466da>)
    at /usr/include/c++/6.3.1/functional:251
#14 0x00000000006b588c in std::_Mem_fn_base<void (Astroid::Poll::*)(), true>::operator()<Astroid::Poll*>(Astroid::Poll*&&) const (this=0xeee310, __args#0=<unknown type in /usr/bin/astroid, CU 0x316390, DIE 0x3466da>)
    at /usr/include/c++/6.3.1/functional:604
#15 0x00000000006b5857 in std::_Bind_simple<std::_Mem_fn<void (Astroid::Poll::*)()> (Astroid::Poll*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0xeee308)
    at /usr/include/c++/6.3.1/functional:1391
#16 0x00000000006b57a5 in std::_Bind_simple<std::_Mem_fn<void (Astroid::Poll::*)()> (Astroid::Poll*)>::operator()() (this=0xeee308)
    at /usr/include/c++/6.3.1/functional:1380
#17 0x00000000006b5784 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<v---Type <return> to continue, or q <return> to quit---
oid (Astroid::Poll::*)()> (Astroid::Poll*)> >::_M_run() (this=0xeee300)
    at /usr/include/c++/6.3.1/thread:197
#18 0x00007fffee7e558f in std::execute_native_thread_routine(void*) (__p=0xeee300)
    at /build/gcc-multilib/src/gcc/libstdc++-v3/src/c++11/thread.cc:83
#19 0x00007fffedfe92e7 in start_thread () at /usr/lib/libpthread.so.0
#20 0x00007fffedd2a54f in clone () at /usr/lib/libc.so.6
```

FWIW: I started astroid with `-l /home/max/astroid/astroid.log`

**Comment by gauteh** [comment]
Max writes on mai 29, 2017 15:39:
> I'm on *7a92d and the crashes still happen regularly:

Thanks, this is a very useful stacktrace!

**Comment by gauteh** [comment]
Gaute Hope writes on mai 30, 2017 9:58:
> Max writes on mai 29, 2017 15:39:
>> I'm on *7a92d and the crashes still happen regularly:
> 
> Thanks, this is a very useful stacktrace!

Latest master might be better.
