### ISSUE TITLE
Crashed due to Gio::Error

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#573]
i have an email that crashes astroid. `alot` can show that email just fine. i have no clue yet whats wrong with that email, this is the log/backtrace:

```
[12:36:36] [0x00007ffff7f94140] [M] [debug] ae: sending: AddMessage
[12:36:36] [0x00007ffff7f94140] [M] [debug] ae: send (sync) waiting for lock..
[12:36:36] [0x00007ffff7f94140] [M] [debug] ae: send (sync) lock acquired.
terminate called after throwing an instance of 'Gio::Error'
terminate called after throwing an instance of 'Gio::Error'

Thread 1 "astroid" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: not found.
(gdb) where
#0  0x00007fffebc12bcb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffebbfd875 in __GI_abort () at abort.c:79
#2  0x00007fffec5c5307 in  () at /usr/lib/libstdc++.so.6
#3  0x00007fffec5e8df6 in  () at /usr/lib/libstdc++.so.6
#4  0x00007fffec5e8e31 in  () at /usr/lib/libstdc++.so.6
#5  0x00007fffec5e9063 in  () at /usr/lib/libstdc++.so.6
#6  0x00007ffff0963447 in Gio::Error::throw_func(_GError*) () at /usr/lib/libgiomm-2.4.so.1
#7  0x00007ffff04074a1 in Glib::Error::throw_exception(_GError*) () at /usr/lib/libglibmm-2.4.so.1
#8  0x00007ffff0983f85 in Gio::OutputStream::write_all(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long&) ()
    at /usr/lib/libgiomm-2.4.so.1
#9  0x000055555591b583 in Astroid::AeProtocol::send_message(Astroid::AeProtocol::_MessageTypes, google::protobuf::Message const&, Glib::RefPtr<Gio::OutputStream>) (mt=Astroid::AeProtocol::AddMessage, m=..., ostream=...) at ../src/modes/thread_view/webextension/ae_protocol.cc:62
#10 0x000055555591bebc in Astroid::AeProtocol::send_message_sync(Astroid::AeProtocol::_MessageTypes, google::protobuf::Message const&, Glib::RefPtr<Gio::OutputStream>, std::mutex&, Glib::RefPtr<Gio::InputStream>, std::mutex&) (mt=Astroid::AeProtocol::AddMessage, m=..., ostream=..., m_ostream=..., istream=..., m_istream=...)
    at ../src/modes/thread_view/webextension/ae_protocol.cc:101
#11 0x000055555590f3a9 in Astroid::PageClient::add_message(Glib::RefPtr<Astroid::Message>) (this=0x55555653cb30, m=...) at ../src/modes/thread_view/page_client.cc:358
#12 0x00005555558df4cb in Astroid::ThreadView::add_message(Glib::RefPtr<Astroid::Message>) (this=0x5555561fc000, m=...) at ../src/modes/thread_view/thread_view.cc:490
#13 0x00005555558dea6b in Astroid::ThreadView::render_messages() (this=0x5555561fc000) at ../src/modes/thread_view/thread_view.cc:430
#14 0x00005555558de76a in Astroid::ThreadView::on_ready_to_render() (this=0x5555561fc000) at ../src/modes/thread_view/thread_view.cc:414
#15 0x00005555558dd967 in Astroid::ThreadView::on_load_changed(_WebKitWebView*, WebKitLoadEvent) (this=0x5555561fc000, load_event=WEBKIT_LOAD_FINISHED)
    at ../src/modes/thread_view/thread_view.cc:310
#16 0x00005555558dd7a0 in Astroid::ThreadView_on_load_changed(WebKitWebView*, WebKitLoadEvent, gpointer) (w=0x5555562d2bd0, load_event=WEBKIT_LOAD_FINISHED, user_data=0x5555561fc000) at ../src/modes/thread_view/thread_view.cc:294
#17 0x00007ffff1b56c3d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff1b699c3 in  () at /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff1b72952 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff1b72f9f in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff577b70e in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#22 0x00007ffff559912d in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#23 0x00007ffff56862b7 in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#24 0x00007ffff57495fd in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#25 0x00007ffff568171b in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#26 0x00007ffff5682315 in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#27 0x00007ffff2cbb5fd in WTF::RunLoop::performWork() () at /usr/lib/libjavascriptcoregtk-4.0.so.18
#28 0x00007ffff2cf0f59 in  () at /usr/lib/libjavascriptcoregtk-4.0.so.18
---Type <return> to continue, or q <return> to quit---
#29 0x00007ffff1878508 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#30 0x00007ffff18788f8 in  () at /usr/lib/libglib-2.0.so.0
#31 0x00007ffff187898c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#32 0x00007ffff3047b5d in g_application_run () at /usr/lib/libgio-2.0.so.0
#33 0x00005555557cff8e in Astroid::Astroid::run(int, char**) (this=0x555555d3fc00, argc=1, argv=0x7fffffffe9d8) at ../src/astroid.cc:322
#34 0x00005555557cb92e in main(int, char**) (argc=1, argv=0x7fffffffe9d8) at ../src/main.cc:5
(gdb) 
```

**Comment by gauteh** [comment]
Could be caused by an exception in the threadview extension. Do you have 
a chance to attach gdb to the webprocess and then trigger the crash to 
see if you get a backtrace there? Or if you have a core file possibly.

**Comment by gauteh** [comment]
Also, it is difficult to debug without a test message to reproduce the crash.

**Comment by gauteh** [comment]
Need more info, will be happy to re-open with a test case that re-produces the crash.

**Comment by gauteh** [comment]
This turned out to be a deeper error than I first thought. Apparently 
char[n] allocations (with n non-const) is techinically not allowed in 
C++. In this case it seems to cause an weird error: I was not able to 
access the *middle* of the buffer array. However, start and end just 
fine. By using the correct new[] and delete[] things seem to work.

Might have to turn on -pedantic. Can you try #580?

**Comment by emdete** [comment]
yes, that fixes the issue. thank you.
